[workspace]
authors = ["Ben Mares <services-git-throwaway2@tensorial.com>"]
channels = ["conda-forge"]
name = "matern"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=7.1.0,<8"
jupyter = ">=1.1.1,<2"
matplotlib = ">=3.10.7,<4"
ipywidgets = ">=8.1.8,<9"
xarray = ">=2025.10.1,<2026"
scipy = ">=1.16.3,<2"
